# Source: https://github.com/actions/starter-workflows/blob/main/ci/go.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  # Test golangci-lint for go-version define in go.mod
  golangci:
    runs-on: ubuntu-24.04
    steps:
      - name: Install harfbuzz
        run: sudo apt-get install libharfbuzz-dev
      - name: Set PKG_CONFIG_PATH
        run: export PKG_CONFIG_PATH=/usr/include/harfbuzz
      - name: Install GCC
        run: sudo apt-get install gcc
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.0.0
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b #v5.4.0
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd #v7.0.0
        with:
          version: latest
          only-new-issues: true

  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Install harfbuzz
        run: sudo apt-get install libharfbuzz-dev
      - name: Set PKG_CONFIG_PATH
        run: export PKG_CONFIG_PATH=/usr/include/harfbuzz
      - name: Install GCC
        run: sudo apt-get install gcc
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.0.0
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b #v5.4.0
        with:
          go-version-file: go.mod
          cache: false
      - name: Test
        run: go test -v ./...
