# Source: https://github.com/actions/starter-workflows/blob/main/ci/go.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  # Test golangci-lint for go-version define in go.mod
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Install harfbuzz
        run: sudo apt-get install libharfbuzz-dev
      - name: Set PKG_CONFIG_PATH
        run: export PKG_CONFIG_PATH=/usr/include/harfbuzz
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install gcc
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe #v4.1.0
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc #v3.7.0
        with:
          version: latest
          only-new-issues: true
