# Source: https://github.com/actions/starter-workflows/blob/main/ci/go.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  # Test golangci-lint for go-version define in go.mod
  golangci:
    runs-on: ubuntu-24.04
    steps:
      - name: Install harfbuzz
        run: sudo apt-get install libharfbuzz-dev
      - name: Set PKG_CONFIG_PATH
        run: export PKG_CONFIG_PATH=/usr/include/harfbuzz
      - name: Install GCC
        run: sudo apt-get install gcc
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.0.0
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed #v5.1.0
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 #v6.1.1
        with:
          version: latest
          only-new-issues: true

  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Install harfbuzz
        run: sudo apt-get install libharfbuzz-dev
      - name: Set PKG_CONFIG_PATH
        run: export PKG_CONFIG_PATH=/usr/include/harfbuzz
      - name: Install GCC
        run: sudo apt-get install gcc
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.0.0
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed #v5.1.0
        with:
          go-version-file: go.mod
          cache: false
      - name: Test
        run: go test -v ./...
