# Source: https://github.com/actions/starter-workflows/blob/main/ci/go.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  # Test golangci-lint for go-version define in go.mod
  golangci:
    runs-on: ubuntu-24.04
    steps:
      - name: Install harfbuzz
        run: sudo apt-get install libharfbuzz-dev
      - name: Set PKG_CONFIG_PATH
        run: export PKG_CONFIG_PATH=/usr/include/harfbuzz
      - name: Install GCC
        run: sudo apt-get install gcc
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.0.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 #v5.0.2
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 #v6.0.1
        with:
          version: latest
          only-new-issues: true

  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Install harfbuzz
        run: sudo apt-get install libharfbuzz-dev
      - name: Set PKG_CONFIG_PATH
        run: export PKG_CONFIG_PATH=/usr/include/harfbuzz
      - name: Install GCC
        run: sudo apt-get install gcc
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.0.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 #v5.0.2
        with:
          go-version-file: go.mod
          cache: false
      - name: Test
        run: go test -v ./...
